- README.md
> Add CAIP Index to README

- CAIPs/caip-10.md
Updates to CAIP-10:
* Add Kusama Network to test cases
* Fixes Dummy Max Length bytes calculation
> Update Test Cases for CAIP-10

- CAIPs/caip-13.md
- CAIPs/caip-2.md
- CAIPs/caip-27.md
- CAIPs/caip-3.md
- CAIPs/caip-4.md
- CAIPs/caip-5.md
This PR covers an update to CAIP-2 and corresponding namespace CAIPs to include resolution methods to resolve blockchain references for each namespace
> Blockchain namespace resolvers

- CAIPs/caip-27.md
Targeted JSON-RPC requests to a specific CAIP-2 chainId
> CAIP-27: JSON-RPC Provider Request

- CAIPs/caip-26.md
This PR adds chain-id for Tezos to the list.
Let me know if a seperate issue has to be created to track this PR
> CAIP-26 | Blockchain reference for Tezos

- CAIPs/caip-10.md
- CAIPs/caip-25.md
- CAIPs/caip-27.md
As discussed on CASA Meeting #1, it reached consensus that CAIP-10 should change endianness as proposed on Issue #51
> CAIP-10 Proposed Changes

- CAIPs/caip-76.md
- CAIPs/caip-hedera-account-reference.md
Describe the Account ID format for Hedera
Signed-off-by: Danno Ferrin <danno.ferrin@hedera.com>
> Hedera Account ID

- CAIPs/caip-25.md
> Corrected typos on caip-25

- CAIPs/caip-1.md
> Feat/scope expansion in CAIP-1

- CAIPs/caip-2.md
I made several changes here, including an attempt to make line 43 into a coherent sentence. If I have misunderstood the intention of that line, please correct.
> Proofreading and grammatical checks

- CAIPs/caip-1.md
Running through the CAIPs one by one to ensure they conform with standard English usage and are free from error. To the greatest extent possible :-P
> Proofreading and grammatical fixes

- CAIPs/caip-74.md
> update cacao example

- Gemfile.lock
according to this
https://stackoverflow.com/a/73079138
> fix bundle in gemlock for runner deploy

- CAIPs/caip-1.md
- CAIPs/caip-10.md
- CAIPs/caip-104.md
- CAIPs/caip-13.md
- CAIPs/caip-19.md
- CAIPs/caip-21.md
- CAIPs/caip-22.md
- CAIPs/caip-23.md
- CAIPs/caip-26.md
- CAIPs/caip-27.md
- CAIPs/caip-28.md
- CAIPs/caip-3.md
- CAIPs/caip-30.md
- CAIPs/caip-4.md
- CAIPs/caip-5.md
- CAIPs/caip-74.md
- CAIPs/caip-76.md
- Gemfile.lock
- _data/statuses.yml
See https://eips.ethereum.org/EIPS/eip-1 , in particular https://eips.ethereum.org/assets/eip-1/EIP-process-update.jpg
> Update CAIP 1 (and publishing automation) to better reflect EIP lifecycle stations

- CAIPs/caip-122.md
in the EIP process, we're ready to mark as "In review" as soon as the authors mark it as such.  here, I wonder if there should be some kind of "in prod" and/or "two implementations" requirement, but that's a bigger question for thursday  :D
> Update caip-122.md status to review

- CAIPs/caip-1.md
- CAIPs/caip-25.md
- CAIPs/caip-3.md
- CAIPs/caip-76.md
- caip-template.md
Currently working on a CAIP checker that can check headers for correctness - this removes some inconsistencies
> Formal fixes

- CAIPs/caip-122.md
> Add wallet implementer considerations

- README.md
Linking CAIP Index to homepage
> Update CAIP Index

- CAIPs/caip-10.md
> Make caip-10 final

- README.md
> Last Call -> Review

- CAIPs/caip-211.md
- CAIPs/caip-222.md
- CAIPs/caip-27.md
- CAIPs/caip-76.md
> fix yaml arrays in requires frontmatter field

- CAIPs/caip-25.md
- CONTRIBUTING.md
- README.md
- caip-template.md
> [Admin] Add Style Guide to Contributing.md and template

- CAIPs/caip-222.md
> CAIP-222: Fix wrong link

- CAIPs/caip-74.md
> Fix malformed markdown links and lint markdown in CAIP-74

- CAIPs/caip-358.md
some basic privacy considerations I promised to submit awhile ago
> add privacy considerations for CAIP-358
