ChainAgnostic/CAIPs

- CAIPs/caip-23.md
- CAIPs/caip-draft_filecoin_namespace.md
- README.md
This pull request adds CAIP-2 chain id for Filecoin.
> CAIP-23: Blockchain Reference for Filecoin Namespace

- CAIPs/caip-7.md
- README.md
Initial draft of the CAIP-2 for EOSIO blockchains.
> Implementation of CAIP-2 for EOSIO blockchains

- CAIPs/caip-1.md
- caip-template.md
The `updated:` field was set in all documents except CAIP-1 and the template
> Add updated field to template

- README.md
There were two CAIPs merged to master missing from the index. cc @ligi
> Update CAIP Index

- CAIPs/caip-10.md
- CAIPs/caip-19.md
- CAIPs/caip-2.md
- CAIPs/caip-20.md
- CAIPs/caip-3.md
- CAIPs/caip-5.md
This proposal updates maximum lengths for CAIP-2, CAIP-10 and CAIP-19
Previous maximum lengths favored the utf-8 string length within standard sizes like 64 and 128 characters however these included the separators. 
This would then create the situation where namespaces, references and addresses had uncommon maximum lengths (47 and 63)  to accommodate for the separators.
Additionally they were unnecessarily long and since now we have quite a few namespace standards specified under CAIPs we can observe that chain namespaces are no longer than 8 characters and chain references are no longer than 32 characters.
Finally these new proposed maximum lengths allow for cleaner byte encoding with fixed lengths without the need of separators
> Maximum Lengths for CAIPs

- CAIPs/caip-10.md
This updates the "updated" date of the CAIP-10 specification to correspond with its update in #59.
Previous updates to CAIP-10: #49, #15, #10 (creation)
> Update CAIP-10 updated date

- CAIPs/caip-10.md
This PR updates the regex for CAIP-10 chain id to be more specific, by incorporating the regexes for its constitutive CAIP-2 components.
This change is intended to help communicate the structure of a CAIP-10 chain id.
CAIP-10 already specifies, in more than one place, that the chain id is specified by CAIP-2. But an implementer might possibly look at the regex and think that it expresses the whole of the allowed or expected range of characters, without referring to CAIP-2. Implementations incorporating that assumption might then allow processing of account ids that contain chain ids that conform to the more lax regex in CAIP-10 but are invalid according to CAIP-2. This change should help prevent such a problem. Additionally, maybe it could help enable simplifying CAIP-10 implementations, …
> Make CAIP-10 regex incorporate CAIP-2

- CAIPs/caip-74.md
- CAIPs/caip-77.md
- README.md
- Rename cacao draft file to caip-74.md
- Add it to the README
CC @bumblefudge @ligi
> chore: Use CAIP-74 identifier for CACAO

- CAIPs/caip-74.md
---
caip: 74
title: CACAO - Chain Agnostic CApability Object
author: Sergey Ukustov (@ukstv), Haardik (@haardikk21)
discussions-to: https://github.com/ChainAgnostic/CAIPs/pull/74
status: Draft
type: Standard
created: 2021-11-01
updated: 2022-07-12
---
Represent a chain-agnostic Object Capability (OCAP), created using [CAIP-122](), as an [IPLD](https://ipld.io) object.
In this document we define a way to present a result of [CAIP-122]() signing operation as an [IPLD](https://ipld.io)-based object capability (OCAP).
"Sign-in with X" is a way for a user to authenticate into a service, and provide authorization. In essense, it is a signature of a well-formed payload.
We could see this as a stepping point for a _rich_ capability-based authorization system.
In order to do this, we would like to …
> [CAIP-74] Update to support SIWx

- CAIPs/caip-171.md
It was missed in [last PR](https://github.com/ChainAgnostic/CAIPs/pull/173?notification_referrer_id=NT_kwDOABikYbI0ODQ5NDUxNDU4OjE2MTQ5NDU#discussion_r1025399927)
> Add discussions URL to CAIP-171

- CAIPs/caip-25.md
Making dependence on CAIP-171 more explicit as per [last RPC meeting](https://github.com/ChainAgnostic/CASA/issues/52) and hopefully closes #143 unless there are corner-cases to be considered or error-messages to be added?
Signed-off-by: bumblefudge <jcaballero@centre.io>
> to make idempotency more explicit in CAIP25

- CAIPs/caip-25.md
As per yesterday's RPC meeting, this is a straw man of a more verbose CAIP-25 request dividing its params between `required` and `optional` arrays, the latter of which includes session properties.  
This allows a simplified negotation-by-subset of optional authorizations, and a way for providers to override, ignore, or impose their own constraints to the session metadata.  This may offer enough flexibility for everything requested in #141, at the expense of some complexity around corner cases.  It also outsources to #170 the definition of valid properties and their valid values.  Note that there is currently no versioning for #170 objects.
We should decide where "accounts" go as per #144 -- I took the liberty of throwing them into the namespace/chain objects, and allowing all-but-one of …
> Strawman of a CAIP-25 split into required/optional with session properties attached and verbose response

- CAIPs/caip-10.md
- CAIPs/caip-2.md
Adding support for underscores in the chain id reference allows using StarkNet chain ids as-is (`SN_MAIN`, `SN_GOERLI`) without having to do error-prone translations in both dapps and wallets.
Such a change shouldn't impact the existing requirements for the reference.
> Support underscores in chain ID reference

- CAIPs/caip-25.md
Hassan @hmalik88  has been consistently working on this CAIP from the technical perspective and bringing perspective from multiple internal people from MetaMask and so I think his contributions should be recognised.
> Add Hassan Malik to list of authors of CAIP-25

- CAIPs/caip-10.md
- CAIPs/caip-19.md
Many chains naturally use 32 bytes to represent addresses, which translates to 64 characters.
However, it's also common to prefix addresses with `0x`, increasing the character length by two and going over this limit.
To avoid issues between dapps and wallets having to handle removing or adding this prefix, this proposal increases the max length 128 to accommodate more chains without introducing error-prone string manipulations in both dapps and wallets.
> Increase `account_address` and `asset_reference` max length

- CAIPs/caip-171.md
Some options to use here would be UUIDv4 (122 bits of entropy - 128 bits with 6 bits fixed), a SHA-256 hash of the ephemeral public key, or a CSPRNG generated number.
> Add CSPRNG usage requirement

- CAIPs/caip-211.md
- CAIPs/caip-217.md
- _includes/discussion_links.html
- caip-template.md
I'm having trouble getting to the bottom of this typing chaos across yaml and random ruby/liquid dependencies of jekyll, so in the meantime i'm just manually reformatting the offending yaml array and putting a guide into the template so that PR authors don't fall into the same trap.  Going on record here to say that ducktyping is bad.
> Quick-fix for jekyll rendering bug

- CAIPs/caip-211.md
- CAIPs/caip-217.md
- CAIPs/caip-27.md
- cleaned up division of labor between 27, 211, and 217 a bit
- rewrote abstract, rationale, etc; added syntax section
- introduced "assumed" values (which make an ass out of wallet and caller alike), as opposed to "implicit" (but consensual and specified) values; refered to this 3-way enum throughout
- beefed up security and privacy considerations
+ fingerprinting resistance, i.e. no hints whether wallet lacks capabilities or just chooses not to authorize them yet
+ guidance on wallets processing requests containing unknown RPC values
+ guidance on that awkward phase before implicit values can be published namespace-wide
+ more explicit/normative language around parsing ordered arrays
+ fixed bug in CAIP-25 example and added another security posture to it
> Overhaul CAIP-211

- CAIPs/caip-122.md
As noted in https://github.com/ChainAgnostic/namespaces/issues/41#issuecomment-1500659237 and https://github.com/ChainAgnostic/namespaces/issues/66 CAIP-122 is ambiguous.
We define `address` in data model as CAIP-10 account. String representation of singing input though uses plain `${address}` field, and `${chain-id}` that the data model does not even mention.
The PR here resolves the ambiguity. Data model remains the same, with `address` being CAIP-10. String representation is clarified to reflect two fields (previously `${address}` and `${chain-id}`) are derived from data model's `address`.
> editorial: Clarify string representation of CACAO signing input

- CAIPs/caip-122.md
- CAIPs/caip-25.md
- CONTRIBUTING.md
- README.md
- caip-template.md
First 4 commits are just editorial cleanup, only changes that risk being normative are contained in [this one commit](https://github.com/ChainAgnostic/CAIPs/pull/247/commits/028a16bfda277225b774a560b97aaa898e6c9b9b)
> [Errata - CAIP-122] clarify language, make `signatureMeta.t` requirement more explicit

- CAIPs/caip-25.md
As discussed on yesterday's call, CAIP-25 went to final with a dependency on another CAIP which never left draft PR state, and was otherwise ambiguous about undefined properties in the protocol objects. 
This patch would include a SHOULD on dropping any properties not defined in 25, 217, or in a future CAIP.  This leaves open the possibility of additional properties being defined in future CAIPs.
I also included a clarification on the intention of sessionProperties that explicitly includes support or extension of CAIP-25 logic.
I deliberately left open whether extension-CAIPs should announce themselves in sessionProperties flags defined in those CAIPs-- some extension CAIPs might want to give the respondent a way to acknowledge understanding the additional props …
> errata CAIP-25 - drop undefined props

- CAIPs/caip-222.md
Updated [CAIP-222](https://github.com/ChainAgnostic/CAIPs/blob/main/CAIPs/caip-222.md) to support multi-chain authentication.
Added ability to 
- request signatures for multiple chains in a single request
- specify supported signing types via `signatureTypes` request parameter
- respond with a list of signed CACAOs
> feat(caip-222): multi-chain wallet authentication

- CAIPs/caip-25.md
Removes `wallet_switchEthereumChain` from CAIP-25 examples. CAIP-25 providers do not have a concept of "currently selected chains", and the inclusion of this method in the examples is therefore confusing.
> Remove `wallet_switchEthereumChain` from CAIP-25 examples

- CAIPs/caip-275.md
- Updates CAIP-275 in both the filename and header to account for CAIP number assignment. 
Should fix any problems with the CAIP website as well.
> Update formatting number for CAIP-275

- CAIPs/caip-74.md
No normative changes-- just bringing CAIP-74 up to date with the links section of the styleguide that was added to contributing.md since it was ratified.
> Errata: update links section of CAIP-74

- CAIPs/caip-25.md
- CAIPs/caip-27.md
Move from "provider" to "wallet" terminology for CAIP-25 and CAIP-27
> Rename "provider" to "wallet"

- CAIPs/caip-217.md
- CAIPs/caip-25.md
As per last two meetings of RPC WG, I made namespace-wide scope objects explicitly "ALL/only specified chains" rather than "ANY" to discourage "wildcard" semantics.  (See third commit for clear delta).
First commit was just long-overdue cleanup of CAIP-25 editorially to make for cleaner deltas in this and future RPC WG PRs.
Second commit was a related normative but nonbreaking change: I realized it was never explicit that `requiredScopes`, `optionalScopes`, and `sessionScopes` can't have redundant keys.
> [Caip-25] make-wildcard-ban-more-explicit

- CAIPs/caip-275.md
Following comments on  #290 (and [this comment](https://github.com/ChainAgnostic/CAIPs/pull/275#issuecomment-2167321691)) we expand some more on how to treat the `chain` property in authentication config. Also we remove the need for an extra request that can cause issues or degrade UX when using different wallets for authentication and other things
> CAIP-275: remove extra request and expand on chain property usage

- CAIPs/caip-319.md
- CAIPs/caip-x.md
CAIP-319 defines a JSON-RPC method for a wallet to send notifications to a
caller in a specified context defined by a valid [scopeObject][CAIP-217] and,
optionally, tagged with a [sessionId][CAIP-171] for maintaining session
continuity.
This proposal aims to define a standard method for wallets to send notifications
to callers regarding events or state changes related to a specific,
previously-authorized target chain (such as nodes of a specific blockchain or
consensus community within a protocol). It requires a valid
[scopeObject][CAIP-217]. It MAY be tagged with a [sessionId][CAIP-171] if the
[CAIP-25][] session in which it is authorized is keyed by a sessionId (see
[CAIP-316][] for more details). These two properties MAY be inherited from a
persistent session created by [CAIP-25][], …
> Standardize CAIP-2 Scoped Notification Support

- CAIPs/caip-25.md
Thanks to @shanejonas for pointing this out on this week's JSON-RPC WG call. NB @adonesky1 for second review if shane doesn't 😄
> [Errata] Caip 25 normative text still referred to top-level objects as "arrays"

- CAIPs/caip-104.md
As per #329 .  The affected section renders like this on Chrome, at least using `bundle exec jekyll serve` preview on `localhost`:
I'm so embarrassed I won't post a "before" image for comparison 🙈
> Editorial / fix CAIP-104 header value section formatting

- CAIPs/caip-345.md
- CAIPs/caip-draft_wallet_service.md
This proposal defines the wallet service property, `caip345`, for use in CAIP-25. Wallets set this to indicate that certain methods, instead of being handled by the CAIP-25 session, will instead be sent to a JSON-RPC HTTP endpoint. Compatible apps that support this will be able to call these RPC methods, without interactivity with the actual wallet application or user.
> CAIP-345: Wallet service URL property

- CAIPs/caip-341.md
- CAIPs/caip-x.md
Defining extension id as a valid target type for wallet data.
> CAIP-341 - Extension ID Target Type Specification
